extends:
  - react-app
  - plugin:jsx-a11y/recommended
  - airbnb
  - prettier
  - prettier/react
plugins:
  - import
  - jsx-a11y
  - prettier
  - react
env:
  browser: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType: "module"
  ecmaFeatures:
    jsx: true
globals:
  IntlRelativeFormat: false
  isNaN: false
settings:
  import/resolver:
    babel-module:
rules:
  # Single line conditionals are more difficult to set breakpoints on.
  curly:
    - error
    - all

  # While I personally prefer stateless functional components, since not every
  # component can be one, I'd rather be consistent and extend React.Component.
  react/prefer-es6-class: 2
  react/prefer-stateless-function: 0

  # Little practical value in making the distinction
  react/jsx-filename-extension: 0

  # Moving to flowtype
  react/forbid-prop-types: 0

  # Avoid conflicts with Prettier
  react/jsx-indent: 0

  # https://github.com/prettier/prettier#eslint
  prettier/prettier: error

  # We use underscores to prefix "private" class methods
  no-underscore-dangle: 0

  # babel-plugin-module-resolver aliases absolute paths to the src directory
  import/no-absolute-path: 0

  # ...
  react/destructuring-assignment: 0
  prefer-destructuring: 0
  import/prefer-default-export: 0

  # Conflicts with macros
  import/named: 0

  # Conflicts with toasts, may re-enable later
  jsx-a11y/mouse-events-have-key-events: 0
