singleQuote: false
semi: true
tabWidth: 2
trailingComma: all
printWidth: 80
overrides:
  - files: "*.yml"
    options:
      parser: yaml
      semi: false
  - files: ["*.tsx", "*.ts"]
    options:
      parser: typescript
      arrowParens: always
